version: "3"
services:
  flightsmongodb:
    image: mongo:latest
    container_name: "flightsmongodb"
    ports:
      - 27018:27017
    hostname: flightsmongodb
#    volumes:
#      - C:\data\db
  flights:
    image: flights:1.0
    container_name: flights
    ports:
      - 8086:8086
    hostname:  flights
    links:
      - flightsmongodb