grpc:
  client:
    user-service:
      address: static://localhost:6565
      negotiationType: plaintext
    room-service:
      address: static://localhost:7575
      negotiationType: plaintext
server:
  port: 8085

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
